In [1]:
import numpy as np

In [3]:
array = np.array([1, 2, 3, 4, 5, 6])
array

array([1, 2, 3, 4, 5, 6])

In [4]:
arrays_dividios = np.split(array, 3) # dividir o array em 3 partes
arrays_dividios

[array([1, 2]), array([3, 4]), array([5, 6])]

In [5]:
for i, value in enumerate(arrays_dividios):
    print(f"parte {i+1} -> {value}")
    

parte 1 -> [1 2]
parte 2 -> [3 4]
parte 3 -> [5 6]


In [10]:
# Criando um array com 1 dimensão com temperaturas diarias de um mês (30 dias)
temperaturas = np.array([22, 21, 20, 23, 22,
                         24, 24, 23, 22, 20,
                         21, 22, 19, 19, 18,
                         21, 21, 22, 23, 23, 
                         24, 23, 24, 23, 22,
                         22, 23, 24, 23, 20, 
                         22, 23])
temperaturas

array([22, 21, 20, 23, 22, 24, 24, 23, 22, 20, 21, 22, 19, 19, 18, 21, 21,
       22, 23, 23, 24, 23, 24, 23, 22, 22, 23, 24, 23, 20, 22, 23])

In [11]:
semanas = np.split(temperaturas, 4) # dividindo o mes por quatro semanas
semanas

[array([22, 21, 20, 23, 22, 24, 24, 23]),
 array([22, 20, 21, 22, 19, 19, 18, 21]),
 array([21, 22, 23, 23, 24, 23, 24, 23]),
 array([22, 22, 23, 24, 23, 20, 22, 23])]

In [12]:
for i, value in enumerate(semanas):
    print(f"Semana {i+1}: {value}")

Semana 1: [22 21 20 23 22 24 24 23]
Semana 2: [22 20 21 22 19 19 18 21]
Semana 3: [21 22 23 23 24 23 24 23]
Semana 4: [22 22 23 24 23 20 22 23]


In [13]:
media_semanas = [np.mean(semana) for semana in semanas]
media_semanas


[22.375, 20.25, 22.875, 22.375]

In [14]:
for i, value in enumerate(media_semanas):
    print(f"Média da semana {i+1}: {value: .2f}c")

Média da semana 1:  22.38c
Média da semana 2:  20.25c
Média da semana 3:  22.88c
Média da semana 4:  22.38c
