In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [3]:
# Pesquisar a posição valor 30
posicao = np.where(array==30)
posicao

(array([2]),)

In [4]:
# Criar uma array com notas de alunos
notas = np.array([55, 67, 72, 48, 90, 85, 60, 50])
notas

array([55, 67, 72, 48, 90, 85, 60, 50])

In [ ]:
# Pesquisar quais alunos foram aprovados
alunos_aprovados = np.where(notas >= 60) # vai passar os indices> (array([1, 2, 4, 5, 6]),)
alunos_aprovados

(array([1, 2, 4, 5, 6]),)

In [ ]:
# Notas que foram aprovadas
notas[alunos_aprovados]  # array([67, 72, 90, 85, 60])


array([67, 72, 90, 85, 60])

In [7]:
nota_maxima = np.max(notas)
nota_maxima

90

In [ ]:
indice_nota_maxima = np.argmax(notas)
indice_nota_maxima # está no indice 4

4