In [2]:
import numpy as np


In [3]:
# Arrray de um dimensão
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.ndim) # número de dimensões
print(array_1d.shape) # formato do array
array_1d
# Muito usado em listas de dados, series temporais ou coleções de valores

1
(5,)


array([1, 2, 3, 4, 5])

In [ ]:
# Array de duas dimensões
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.ndim)
print(array_2d.shape)
array_2d
# Duas dimensões, duas linhas e três colunas, se transformando numa matriz. Muito usado em matrizes, tabelas de dados e imagens em escada de cinza

2
(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Array de três dimensões
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d.ndim)
print(array_3d.shape)
array_3d
# ficou 4 linhas e duas colunas, utilizado em Imagens em cores(Cada matriz representando um canal de cor, como RGB)

3
(1, 4, 2)


array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [ ]:
# Array quadimensional
array_4d = np.zeros((2, 3, 4, 5))
print(array_4d.ndim)
print(array_4d.shape)
array_4d
# 

4
(2, 3, 4, 5)


array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])