In [1]:
import numpy as np


In [2]:
array = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])
array
print(array.ndim)
print(array.shape)

2
(3, 3)


In [26]:
# Buscando elemento na linha 1 e coluna 2
elemento = array[1, 2] # linha 1, coluna 2. Resultado: 60
elemento

60

In [27]:
# Pegando dados apenas da linha 0
linha_0 = array[0] # Resultado: array([10, 20, 30])
linha_0

array([10, 20, 30])

In [28]:
# Acessando coluna 1
coluna_1 = array[:, 1] # Resposta array([20, 50, 80])
coluna_1

array([20, 50, 80])

In [29]:
# Fatiando para obter um subarray
# linha 0 a 1 | Coluna 2 a 1
subarray = array[0:2, 1:3]
subarray

array([[20, 30],
       [50, 60]])

In [30]:
mascara = array > 50 # Vai chamar os itens maiores que 50, que vai dar true para maiores e false para menores
mascara

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
# Filtrando elementos
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50 # resposta: array([60, 70, 80, 90]) 

array([60, 70, 80, 90])

In [32]:
# Modificando elementos
array[1, 1] = 100 # Array na linha 1, coluna 1, muda pra 100
array


array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])