In [1]:
import numpy as np



In [2]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [ ]:
# soma
soma = np.add(array, 10) # somando a lista com dez = array([11, 12, 13, 14, 15])
soma

array([11, 12, 13, 14, 15])

In [ ]:
# Subtração
subtracao = np.subtract(array, 5) # Subtraindo a lista com 5 = array([-4, -3, -2, -1,  0])
subtracao

array([-4, -3, -2, -1,  0])

In [ ]:
# multipicação
multiplicacao = np.multiply(array, 2)  # multiplicando por 2 = array([ 2,  4,  6,  8, 10])
multiplicacao

array([ 2,  4,  6,  8, 10])

In [ ]:
# divisão
divisao = np.divide(array, 2) # Dividindo por 2 = array([0.5, 1. , 1.5, 2. , 2.5])
divisao

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
# Funções trigonometricas
seno = np.sin(array) # array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

coseno = np.cos(array) # array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])
coseno

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
# Funções estatísticas
media = np.mean(array) # Média =  3
media

3.0

In [11]:
# Desvio padrão
desvio_padrão = np.std(array)
desvio_padrão

1.4142135623730951

In [ ]:
# Funções de comparação
comparacao_maior_que_3 = array > 3  # array([False, False, False,  True,  True])
comparacao_maior_que_3

array([False, False, False,  True,  True])

In [ ]:
# Combinando funções
resultado = np.sqrt(array) + np.power(array, 2) # sqtr é potencia e np.power está elevando a potencia a 2 = array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])
resultado

array([ 2.        ,  5.41421356, 10.73205081, 18.        , 27.23606798])

In [ ]:
# Funções exponenciais
exponencial = np.exp(array)  # array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
#       148.4131591 ])
exponencial

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
# Função de logaritmo
logaritmo = np.log(array) # array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])
logaritmo

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
# Função de arredondamento
arrendodado = np.round(array / 2)  # array([0., 1., 2., 2., 2.])
arrendodado


array([0., 1., 2., 2., 2.])

In [ ]:
# Função de poetencia
potencia = np.power(array, 3) # array([  1,   8,  27,  64, 125])
potencia

array([  1,   8,  27,  64, 125])