Copy
Uma nova cópia do array é criada em memoria. Isso significa que as duas matrizes (original e copia) são independentes uma da outra.

View
- Não é criada uma nova copia da memoria (por isso a array original pode ser alterada). A View compartilha os mesmos dados que o array original.

In [3]:
import numpy as np

In [4]:
array_original = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

array_original

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Copia rasa (view)
array_view = array_original[1:, 1:] # copia rasa mais fatiamento - Ele altera o array original
array_view


array([[5, 6],
       [8, 9]])

In [ ]:
# Copia profunda
array_copia = array_original.copy() # Não altera o array original
array_copia

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])