In [2]:
import numpy as np


In [3]:
# Criando dois arrays 1d
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])


In [4]:
# Concatenando os arrays
novo_array = np.concatenate((array1, array2))
novo_array

array([1, 2, 3, 4, 5, 6])

In [5]:
# Criando arrays para nomes e notas
nomes = np.array(["Alice", "Bob", "Charlie"])
notas_matematica = np.array([85, 90, 78])
notas_fisica = np.array([88, 79, 90])


In [6]:
# Usando np.vstack para empilhar verticalmente os dados
dados_estudantes = np.vstack((nomes, notas_matematica, notas_fisica))
dados_estudantes

array([['Alice', 'Bob', 'Charlie'],
       ['85', '90', '78'],
       ['88', '79', '90']], dtype='<U21')

In [8]:
# Usando o np.hstack para empilhar horizontalmente
matriz_notas = np.column_stack((notas_matematica, notas_fisica))
matriz_notas

array([[85, 88],
       [90, 79],
       [78, 90]])

In [9]:
# Adicionando uma nova coluna com a média das notas
media_notas = np.mean(matriz_notas, axis=1)
matriz_final = np.column_stack((matriz_notas, media_notas))
matriz_final

array([[85. , 88. , 86.5],
       [90. , 79. , 84.5],
       [78. , 90. , 84. ]])