Testando ipynb

In [1]:
import numpy as np  

In [9]:
# Crie 5 arrays de uma dimensão
array1 = np.array([10, 20, 30, 40, 50])
print(array1)

array2 = np.array([1, 2, 3])
print(array2)

array3 = np.array(["David", "Arthur", "Alinbe"])
print(array3)

array4 = np.array(([20, 30, 40, 50, 60]))
print(array4)

array5 = np.array([100, 200, 300, 400])
print(array5)


[10 20 30 40 50]
[1 2 3]
['David' 'Arthur' 'Alinbe']
[20 30 40 50 60]
[100 200 300 400]


In [17]:
# Crie 5 arrays de duas dimensões e 5 de três dimensões
array2d1 = np.array([[1, 2], [3, 4]])
print(array2d1)

array2d2 = np.array([[5, 6], [7, 8]])
print(array2d2)

array2d3 = np.array([[9, 10], [11, 12]])
print(array2d3)

array2d4 = np.array([[13, 14], [15, 16]])
print(array2d4)

array2d5 = np.array([[17, 18], [19, 20]])
print(array2d5)


array3d1 = np.array([[1, 2], [3, 4], [5, 6]])
print(array3d1)

array3d2 = np.array ([[7, 8], [9, 10], [11, 12]])
array3d3 = np.array([[13, 14], [15, 16], [17, 18]])
array3d4 = np.array([[19, 20], [21, 22], [23, 24]])
array3d5 = np.array([[25, 26], [27, 28], [29, 30]])
print(f"arrays\n{array3d1}, \n{array3d2}, \n{array3d3}, \n{array3d4}, \n{array3d5}")


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
[[13 14]
 [15 16]]
[[17 18]
 [19 20]]
[[1 2]
 [3 4]
 [5 6]]
arrays
[[1 2]
 [3 4]
 [5 6]], 
[[ 7  8]
 [ 9 10]
 [11 12]], 
[[13 14]
 [15 16]
 [17 18]], 
[[19 20]
 [21 22]
 [23 24]], 
[[25 26]
 [27 28]
 [29 30]]


In [6]:
import numpy as np

In [ ]:
# indexação - 
array = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])
array
print(array.ndim)
print(array.shape)
'''
# Busque o elemento na linha 1, coluna 2
buscando = array[1, 2]
buscando

# Busque o elemento na linha 2, coluna 2
buscando2 = array[2, 2]
buscando2

# Busque o elemento na linha 1, coluna 0
buscando3 = array[1, 0]
buscando3

# Pegue dados apenas da linha zero
buscando4 = array[0]
buscando4

# Pegue dados apenas da linha 2
buscando5 = array[2]
buscando5

# Acesse a coluna zero
buscando6 = array[:, 0]
buscando6

# Acesse a coluna 1
buscando7 = array[:, 1]
buscando7

# Acesse  a coluna 2
buscando8 = array[:, 2]
buscando8
'''
# Fatie para obter um subarray - linha 0 a 1, coluna 1 a 2
fatiando = array[0:2, 1:3]
print(f' linha 0 a 1, coluna 1 a 2 {fatiando}')

# Fatie para obter um subarray - linha 1 a 2, coluna 0 a 1
fatiando2 = array[1:3, 0:2]
fatiando2

# Chame os iténs maiores que 30
chame = array > 30
chame

# Chame os iténs maiores que 50
chame2 = array > 50
chame2

# Chame os iténs maiores que 70
chame3 = array > 70
chame3

# Filtre elementos maiores que 30
filtre = array[chame]
filtre

# Filtre elementos maiores que 50
filtre2 = array[chame2]
filtre2

# Filtre elementos maiores que 70
filtre3 = array[chame3]
filtre3

# Modifique o elemento linha 1, coluna 1 para 100
# Modifique o elemmento linha 0, coluna 0, para 110
# Modifique o elemento linha 2, coluna 1 para 800
# 

2
(3, 3)
 linha 0 a 1, coluna 1 a 2 [[20 30]
 [50 60]]


array([80, 90])

In [ ]:
import numpy as np

# Fatiamento
array = np.array([[1, 2, 3, 4, 5], 
                  [6, 7, 8, 9, 10], 
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20]])
array


# Fatie as duas primeiras linhas
# Fatie a primeira linha
# Fatie a linha 2 á 3

